# Generated by Django 6.0.6 on 2026-06-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_genre_language_movie_show_booking_bookedseat_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
