# Generated by Django 6.0.6 on 2026-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_screen_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='row_name',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
