# Generated by Django 6.0.6 on 2026-06-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0006_seat_row_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
    ]
