# Generated by Django 6.0.6 on 2026-06-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_alter_screen_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookedSeat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
