# Generated by Django 6.0.6 on 2026-06-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_remove_booking_show_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='theatre',
            unique_together=set(),
        ),
    ]
