# Generated by Django 6.0.6 on 2026-06-19 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('theatre', '0008_remove_booking_show_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='show',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.show'),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='booking',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='bookedseat',
            name='seat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='theatre.seat'),
        ),
        migrations.AlterUniqueTogether(
            name='bookedseat',
            unique_together={('show', 'seat')},
        ),
    ]
